// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMS7dH3iwxf5vTaz4Ir40iZ04r-mxgc0U',
    appId: '1:41668405235:web:e7560dfd4af818a74cd486',
    messagingSenderId: '41668405235',
    projectId: 'souseleto-33d19',
    authDomain: 'souseleto-33d19.firebaseapp.com',
    storageBucket: 'souseleto-33d19.firebasestorage.app',
    measurementId: 'G-2QTJFH3FD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtFdeIlTWpDnZjyP4piAxfSqNxHk53kn4',
    appId: '1:41668405235:android:cf1745902c568d114cd486',
    messagingSenderId: '41668405235',
    projectId: 'souseleto-33d19',
    storageBucket: 'souseleto-33d19.firebasestorage.app',
  );
}
